"""
Flask web app for predicting wine cultivar using a trained model.

Project structure (for GitHub):

/WineCultivar_Project_yourName_matricNo/
|- app.py
|- requirements.txt
|- /model/
|    |- model_building.ipynb
|    |- wine_cultivar_model.pkl   (generated by the notebook)
|- /static/
|    |- style.css
|- /templates/
     |- index.html
"""

from __future__ import annotations

from pathlib import Path
from typing import Dict, List

import joblib
import numpy as np
from flask import Flask, render_template, request

BASE_DIR = Path(__file__).parent
MODEL_PATH = BASE_DIR / "model" / "wine_cultivar_model.pkl"

app = Flask(__name__)


def load_model():
    """
    Load the trained model and feature metadata.

    Expects the pickle file to contain a dict with:
        - 'model': sklearn Pipeline
        - 'features': List[str] feature names in training order
    """
    if not MODEL_PATH.exists():
        raise FileNotFoundError(
            f"Trained model not found at {MODEL_PATH}. "
            "Open and run 'model_building.ipynb' in the 'model' folder "
            "to create 'wine_cultivar_model.pkl'."
        )
    artifact = joblib.load(MODEL_PATH)
    model = artifact["model"]
    features: List[str] = artifact["features"]
    return model, features


MODEL, FEATURE_ORDER = load_model()


@app.route("/", methods=["GET", "POST"])
def index():
    prediction = None
    probabilities: Dict[str, float] | None = None
    errors: List[str] = []

    if request.method == "POST":
        values = []
        for feature in FEATURE_ORDER:
            raw_val = request.form.get(feature)
            if raw_val is None or raw_val.strip() == "":
                errors.append(f"Missing value for {feature.replace('_', ' ').title()}")
                continue
            try:
                values.append(float(raw_val))
            except ValueError:
                errors.append(
                    f"Invalid numeric value for {feature.replace('_', ' ').title()}"
                )

        if not errors and len(values) == len(FEATURE_ORDER):
            X = np.array([values])
            pred = MODEL.predict(X)[0]
            proba = MODEL.predict_proba(X)[0]
            prediction = int(pred) + 1  # sklearn wine target is 0,1,2 -> Cultivar 1,2,3
            probabilities = {
                f"Cultivar {i+1}": float(p) for i, p in enumerate(proba)
            }

    return render_template(
        "index.html",
        feature_order=FEATURE_ORDER,
        prediction=prediction,
        probabilities=probabilities,
        errors=errors,
    )


if __name__ == "__main__":
    # For local testing:
    #   set FLASK_APP=app.py
    #   flask run
    # or simply: python app.py
    app.run(debug=True)

